### ISSUE TITLE
The latest mod_checklist does not show tabs in Moodle 4

### ISSUE THREAD

**Issue by janvanl** [davosmith/moodle-checklist#104]
Hi,

i ran the update from mod_checklist - 3.9.1.2 to mod_checklist - 3.9.3.2 on a Moodle 4.04 instance.

The old version did work normally, the new version does not show the 3 tab's to edit etc.

Can i downgrade? Or do you plan to make your plugin work on Moodle 4?

I would be gratefull for any hint to get your plugin working again.

Regards,
Jan

**Comment by davosmith** [comment]
Please check the theme you are using is fully compatible with Moodle 4.0 - the tabs in the Moodle 4 version of checklist have been moved to be part of the tabs that are displayed across the top of the page in Moodle 4 compatible themes.

If your theme is not fully compatible, you can find the links in the "settings" block.

**Comment by janvanl** [comment]
Hi, thanks for the fast response.

I have to check this, but have to finish something else first, so in about 2 or 3 hours i will check the theme and the compatibility with moodle 4.

Regards,
Jan

**Comment by davosmith** [comment]
Just to be clear, it has been tested with Moodle 4.0 and 4.1 and the code adjusted to work with the default theme (otherwise it showed duplicated rows of tabs). But, if you use a different theme which does not properly support the Moodle 4.0+ secondary navigation tabs, then the links are shown in the settings block instead.

**Comment by janvanl** [comment]
OK i found Theme "Simplest" and "boost union" that support 4.0 and are similar to Classic we use now.

Regards,
Jan
