### ISSUE TITLE
Duplicate value found in column 'groupingid'

### ISSUE THREAD

**Issue by agrowe** [davosmith/moodle-checklist#41]
For some reason, in one of our Moodle instances we were seeing duplicate groupingid errors on the dashboard when debugging was enabled due to the `checklist_class::get_user_groupings()` function in `locallib.php`.

The error/warning was `Did you remember to make the first column something unique in your call to get_records()? Duplicate value 'xxx' found in column 'groupingid'.`

To remove the warnings, we changed the `SELECT` statement to be `SELECT DISTINCT`. The function now looks like the below

````
    public static function get_user_groupings($userid, $courseid) {
        global $DB;
        $sql = "SELECT DISTINCT gg.groupingid
                  FROM ({groups} g JOIN {groups_members} gm ON g.id = gm.groupid)
                  JOIN {groupings_groups} gg ON gg.groupid = g.id
                  WHERE gm.userid = ? AND g.courseid = ? ";
        $groupings = $DB->get_records_sql($sql, array($userid, $courseid));
        if ($groupings) {
            return array_keys($groupings);
        }
        return array();
    }
````

**Comment by davosmith** [comment]
Thanks for the bug report and sorry for taking a couple of days to reply.

It's a minor warning message, in this case, but I've fixed it as per your suggestion (for such a minor issue I'll wait for the next release before pushing it out to Moodle.org).

Without checking, I assume the problem is that there is a user who belongs to more than one group that are in the same grouping, hence they get the same groupingid twice (or more), via different groups.

Thanks again.

**Comment by agrowe** [comment]
Thanks davo.

I did a bit of initial checking in the DB and it was a weird edge case it looks like. A user was in multiple groups, then each of those groups were in a grouping, but it didn't affect all users it looks like.

Adding the 'distinct' is really just a precaution for the future.

Thanks
