### ISSUE TITLE
Impossible to install plugin with Moodle plugin installer

### ISSUE THREAD

**Issue by dgibaud** [davosmith/moodle-checklist#55]
It is unable to install the plugin via the Moodle plugin installer because it is said that : 

"Débogage de l'output activé
Validation de mod_checklist ... Erreur
  [OK] Nom du plugin à installer [checklist] 
    Aide sur Nom du plugin à installer

 
  [OK] Version du plugin [2018051500] 
  [Erreur] Version de Moodle requise [2017111300] 
Installation interrompue en raison de l'échec de la validation"

**Comment by davosmith** [comment]
My French is limited, but the error seems to state that the version of the plug-in you have tried to install is for 2017111300 - that is Moodle 3.4. So you either need to upgrade your site to Moodle 3.4 (or 3.5), or you need to install the version of my plugin which works with earlier Moodle versions.

**Comment by dgibaud** [comment]
Thanks a lot ! Now, it's OK.
By theway, we use your plugin checklist with flexsections course format, so we need to manually add the activities from the subsections where the checklist activity is installed. And the teacher is obliged to manually ticks the activities like quiz, when there is a grade, that could be automatically validated.

**Comment by davosmith** [comment]
I'm not quite clear what you are asking for here?

Are you asking for me to add some sort of support for the 3rd-party flexsections course format? I've not used the format, so I don't know quite what supporting that would entail.

I'm not sure how the quiz should be automatically validated. Do you mean that the quiz item should be automatically ticked-off if the quiz is completed? If so, then that is an option already - if you configure a completion rule for any activity, then the related checklist item will be automatically ticked-off at the same time (assuming you don't turn that feature off in the checklist configuration).

**Comment by dgibaud** [comment]
Yes, I mean that the item should be automatically ticked-off when the quiz is complted and get a note. The quiz is configured so that a note set the activity completed.

In the below hardcopy Autoevaluation Module I is the name of the quiz
![image](https://user-images.githubusercontent.com/18719433/42560431-ecfa0788-84f6-11e8-8519-e8c491ca7d16.png)

But the student complete the quiz by receiving a note it is not ticked-off in the checklist cause I added it manually

**Comment by dgibaud** [comment]
![image](https://user-images.githubusercontent.com/18719433/42560641-5fa41b48-84f7-11e8-9447-6556519ae6dc.png)

**Comment by davosmith** [comment]
If the checklist item is automatically generated from an activity, then it will be checked-off when the activity itself is completed.

If the checklist item is manually created, then I don't see how I can automatically mark it as checked-off, as I don't have any way of determining which activity should cause that to happen.

**Comment by dgibaud** [comment]
Could it be possible to add an option for the checklist item manually  created to say the way the activity cause the activity completion.

**Comment by davosmith** [comment]
Well that's going to be a reasonable amount of development to try to create a new user interface to link a manually created item to a particular activity and then specify some sort of condition to determine when the item should be checked-off.

This would also make the interface more complex for the vast majority of users who are never going to use such an obscure feature (because I would assume that the standard completion process already takes care of almost all use cases).

If you want to get in contact with my employers via https://www.synergy-learning.com/contact-us/ then we could put together a quote for developing this as a bespoke feature (which might be possible to integrate back into the standard version, in order to maintain it during future upgrades, but it would take a lot of work to come up with a suitable UI). I will not be developing this in my spare time, as it doesn't sound like something that would be useful to most people.
