### ISSUE TITLE
Completion by number instead of percentage?

### ISSUE THREAD

**Issue by sh-csg** [davosmith/moodle-checklist#72]
This plugin has helped me a lot during the time of distance learning. The only thing I was missing is the possibility to set completion criteria to a fixed number of items instead of a percentage. This would be very helpful for with a changing number of activities.

**Comment by davosmith** [comment]
Hi sh-csg - sorry for the slow reply.

I can see that might be a sensible suggestion. It would involve adding an extra drop-down field to select whether you wanted to complete by % or by a fixed number of items. It would need an extra database field to store that value (+ include it in backup and restore) and it would need a couple of lines of code to make it all work.

I'm very unlikely to get around to doing this in my free time (as a general rule, these days, I get paid to work on Moodle code all day, so I don't tend to be very motivated to work on it in evenings). I'd be happy to accept a simple, well-written patch from another developer.

**Comment by davosmith** [comment]
Hi sh-csg - thanks for providing a patch for this.

Unfortunately, when I reviewed the patch, I still found a number of issues with it.

I decided it was going to be quicker for me to simply write the code, rather than keep on giving you feedback on it (well done - at least by showing willing with writing the code, it motivated me to spend a bit of my spare time sorting it out).

Please can you test out the latest commit on the master branch (I'm afraid due to changes I made earlier today to work with Moodle 3.9, this is currently only compatible with that version, but the changes should be possible to cleanly cherry-pick onto the earlier versions)?

Davo
