### ISSUE TITLE
Modules are added even if completion tracking not activated

### ISSUE THREAD

**Issue by nadavkav** [davosmith/moodle-checklist#90]
Some of our teachers found that when auto add section modules is ON, 
the list is populated with modules that have activity completion turn OFF.
I looked at the code, and as far as I can see, 
there is no reference to checking if the module has activity completion set to ON (manual or automatic with rules)

Maybe this is intentional, but I think this should be fixed.
@davosmith What do you think?

**Comment by nadavkav** [comment]
Please see suggested fix from one of my colleagues (@kirildevlion)
https://github.com/devlionco/moodle-checklist/commit/d00a02432fea9b9ad6f4d9a2bbece5ae6d859525

**Comment by davosmith** [comment]
It is entirely intentional. Students still have the option of manually checking-off items that are linked to activities that don't have their own completion conditions. Additionally, there are rules built in to the checklist activity which can determine that an activity is "complete" even if there are no official completion rules enabled.

If you wish to exclude a particular activity, then it is possible to do so by editing the checklist items.

**Comment by nadavkav** [comment]
Thank you @davosmith for your quick and detailed explanation!

> Additionally, there are rules built in to the checklist activity which can determine that an activity is "complete" even if there are no official completion rules enabled.
This was a real surprise to our teachers, as they did not think it was a desired behaviour.

**Comment by nadavkav** [comment]
Adding a link to a similar closed issue I found #52
