### ISSUE TITLE
Behat test failing - course_link.feature

### ISSUE THREAD

**Issue by AdilIqbal95** [davosmith/moodle-checklist#92]
Hi, the test stated above is failing.

**Environment details:**
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_311_STABLE

**Error details:**

**Scenario: An item linked to a course is automatically checked-off when that course is completed**
And I trigger cron: Other backtraces found:
line 2944 of /lib/deprecatedlib.php: call to debugging()
line 172 of /lib/classes/task/legacy_plugin_cron_task.php: call to cron_execute_plugin_type()
line 253 of /lib/cronlib.php: call to core()
line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
line 81 of /admin/cron.php: call to cron_run() (Exception)

**Scenario: An item linked to a course is automatically checked-off if that course is *already* completed**
And I trigger cron: Other backtraces found:
line 2944 of /lib/deprecatedlib.php: call to debugging()
line 172 of /lib/classes/task/legacy_plugin_cron_task.php: call to cron_execute_plugin_type()
line 253 of /lib/cronlib.php: call to core()
line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
line 81 of /admin/cron.php: call to cron_run() (Exception)

**Comment by davosmith** [comment]
On the site where you are running this, do you have any other plugins installed?

The debugging warning, that is causing the failure, indicates that some code on the site is using out of date cron tasks.

You need to contact the maintainer of whichever plugin that is and ask them to update their code to use a scheduled task instead - that will then fix the debugging warning and will allow the tests in my plugin to pass.

To be on the safe side - I've triggered an extra run of the tests, just in case, but you can see that all tests were passing a couple of months ago (and nothing major should have changed in Moodle 3.11 since then): https://github.com/davosmith/moodle-checklist/runs/5433489834?check_suite_focus=true

**Comment by AdilIqbal95** [comment]
Yes we do have other plugins. Thanks for clarifying - will look into this.
