### ISSUE TITLE
Unwanted checklist completion emails

### ISSUE THREAD

**Issue by davosmith** [davosmith/moodle-checklist#93]
See details at: https://moodle.org/mod/forum/discuss.php?d=144764#p1749782

**Comment by davosmith** [comment]
Reading through the code, I think I can see why this would happen.

If something causes the checklist grades to be recalculated (such as the maximum grade changing, or a number of other reasons), then the code to send out the "checklist complete" email only looks at the fact that the checklist is _now_ complete - it doesn't (currently) have any way of spotting that the checklist was _already_ complete (so shouldn't be notified about again).

Unfortunately, there isn't really a sensible data structure I can use to detect this, so I'm going to have to add a new database table to keep track of which checklists each user has already completed and make sure that they don't get notified again. This will take me little while to write (fitting it around my spare time).

**Comment by thart-hub** [comment]
Hello Davo
Greetings from Seward Alaska.  We are currently running Moodle [3.11.6+ (Build: 20220318)] and Checklist 3.9.1.2 
You certainly answered about our flurry of emails.  We did have to change the max grade so there was a recalculation.  

Since we aren't going to recalculate the grades again. probably no need to recreate a database for this.  It is just good to know about the recalculate issue.

I am still wondering what settings will make it so we only get notified when the student self reports on the check list and not for every quiz.  I have set the checklist as restricted before the last quiz is completed .  I attached a screen shot of my settings in the original forum post on moodle.org
Thank you

**Comment by davosmith** [comment]
Thanks for the extra info - the code, is, however, certainly not correct at the moment (although it has been in that incorrect state for many years and hasn't been flagged up before!), so I will certainly make an effort to fix it, as I'm sure it has affected others.

**Comment by davosmith** [comment]
I've updated the code (here in github - but I'll push it out to the Moodle plugins directory at some point).

After the upgrade, it will track which users have / haven't completed the checklist previously and only send out notifications for users at the point where they complete the checklist. If a user updates a checklist to be incomplete, then later updates it again, then the email will only be sent out if it is at least an hour since the last email was sent (this is to prevent a user from sending out lots of emails by simply toggling the same checkbox on and off).
