### ISSUE TITLE
We can't export regular qualifications, only the checklist ones 

### ISSUE THREAD

**Issue by kojix** [davosmith/moodle-checklist#95]
We're running the last version of checklist plugin (3.9.1.2) and gradeexport_checklist on Moodle 4.0, and since we upgraded to 4.0, we can't export the regular course qualifications ( the checklist ones work fine) to any.

In the qualifications exports methods we have:

-gradeexport_checklist
-gradeexport_ods
-gradeexport_txt
-gradeexport_xls
-gradeexport_xml

In the qualifications>Export page, the selector to choose the output format doesn't appear, only the Ckecklist section...

In our pre-production installation where checklist isn't installed (all the other export methods are) it works without problem... 
![Captura_PRO](https://user-images.githubusercontent.com/29885232/176123019-d9ae835e-1590-42b9-9f1d-ab6fbfa2523b.PNG)
![Captura_PRE](https://user-images.githubusercontent.com/29885232/176123025-9a92cbea-3868-4868-8a95-c3b9edd6a2ca.PNG)

**Comment by davosmith** [comment]
Having looked at this, the title is misleading.

The grade exports all work fine (as far as I can tell), the only issue is that there is an undocumented change to the navigation, so now each grade export plugin is expected to include a drop-down list of the other export plugins in order to get to them.

I will see what I can do about this, but in the short term you can access the export plugins directly simply by adjusting the URL (change the word 'checklist' in the URL to 'ods' or 'xls', etc. to access the relevant page).

**Comment by davosmith** [comment]
Spotted the problem - I've pushed a fix to: https://github.com/davosmith/moodle-grade_checklist/commit/ed72d6d38ac2839dac0f8e32ff765332401439fd and I'm waiting on the automated checks to verify it.

(Note this issue is for gradeexport_checklist, not for mod_checklist, so the fix won't show up here on the mod_checklist repository).

**Comment by davosmith** [comment]
Hi,

You can only install gradeexport_checklist on a site that also has
mod_checklist installed - the error seems to be suggesting you're trying to
add it to a site that doesn't have mod_checklist?

Davo

**Comment by davosmith** [comment]
Thanks for confirming. I'll get this version rolled out to the Moodle.org plugins directory.
